-- Jalankan migration ini setelah 20260722000001_add_salary_category.sql.
-- Penarikan dicatat terpisah agar saldo rekening dan progres target tabungan sama-sama berkurang.

alter table public.ledger_entries
  drop constraint ledger_entries_entry_type_check;

alter table public.ledger_entries
  add constraint ledger_entries_entry_type_check
  check (entry_type in ('income', 'expense', 'bill', 'transfer', 'saving', 'saving_withdrawal', 'adjustment'));

alter table public.ledger_entries
  drop constraint ledger_entries_category_check;

alter table public.ledger_entries
  add constraint ledger_entries_category_check
  check (category in ('salary', 'daily', 'personal', 'shopee', 'application', 'savings', 'savings_withdrawal', 'transfer', 'other'));

create table public.savings_withdrawals (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.savings_goals (id) on delete cascade,
  ledger_entry_id bigint not null unique references public.ledger_entries (id) on delete restrict,
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now()
);

create index savings_withdrawals_goal_idx on public.savings_withdrawals (goal_id);

-- Total progres = setoran target dikurangi penarikan dari target tersebut.
create or replace view public.v_savings_goal_progress
with (security_invoker = true) as
with contribution_totals as (
  select goal_id, sum(amount) as total_contributed
  from public.savings_contributions
  group by goal_id
), withdrawal_totals as (
  select goal_id, sum(amount) as total_withdrawn
  from public.savings_withdrawals
  group by goal_id
), goal_balances as (
  select
    g.id,
    g.name,
    g.target_amount,
    g.target_date,
    g.is_active,
    greatest(coalesce(c.total_contributed, 0) - coalesce(w.total_withdrawn, 0), 0) as saved_amount,
    coalesce(w.total_withdrawn, 0) as withdrawn_amount
  from public.savings_goals g
  left join contribution_totals c on c.goal_id = g.id
  left join withdrawal_totals w on w.goal_id = g.id
)
select
  id,
  name,
  target_amount,
  target_date,
  is_active,
  saved_amount,
  greatest(target_amount - saved_amount, 0) as remaining_amount,
  round(saved_amount::numeric / target_amount * 100, 2) as progress_percent,
  withdrawn_amount
from goal_balances;

-- Tambahkan angka penarikan tabungan ke ringkasan bulanan tanpa mengganti kolom yang sudah ada.
create or replace view public.v_monthly_cashflow
with (security_invoker = true) as
select
  date_trunc('month', entry_date)::date as month,
  coalesce(sum(amount) filter (where entry_type = 'income'), 0) as money_in,
  coalesce(sum(amount) filter (where entry_type in ('expense', 'bill')), 0) as total_usage,
  coalesce(sum(amount) filter (where category = 'daily' and entry_type in ('expense', 'bill')), 0) as daily_usage,
  coalesce(sum(amount) filter (where category = 'personal' and entry_type in ('expense', 'bill')), 0) as personal_usage,
  coalesce(sum(amount) filter (where category = 'shopee' and entry_type in ('expense', 'bill')), 0) as shopee_usage,
  coalesce(sum(amount) filter (where category = 'application' and entry_type in ('expense', 'bill')), 0) as application_usage,
  coalesce(sum(amount) filter (where entry_type = 'bill'), 0) as bills_paid,
  coalesce(sum(amount) filter (where entry_type = 'saving'), 0) as saving_added,
  coalesce(sum(amount) filter (where entry_type = 'income' and category = 'salary'), 0) as salary_income,
  coalesce(sum(amount) filter (where entry_type = 'saving_withdrawal'), 0) as saving_withdrawn
from public.ledger_entries
group by 1;

alter table public.savings_withdrawals enable row level security;

create policy "Finance members manage savings withdrawals"
  on public.savings_withdrawals for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());

grant select, insert, update, delete on public.savings_withdrawals to authenticated;
grant usage, select on sequence public.savings_withdrawals_id_seq to authenticated;
grant select on public.v_savings_goal_progress, public.v_monthly_cashflow to authenticated;
