-- MBFinance: skema ringan untuk keuangan Bryan & Maddy.
-- Semua nominal memakai Rupiah tanpa desimal (BIGINT), misalnya 150000 = Rp150.000.
-- Jalankan file ini sekali di Supabase SQL Editor atau sebagai migration Supabase CLI.

create table public.people (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_custodian boolean not null default false,
  auth_user_id uuid unique references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint people_name_not_blank check (char_length(trim(name)) > 0)
);

-- Rekening, kas, e-wallet, dan tabungan yang menyimpan uang bersama.
-- "Uang Bryan" dipakai saat Maddy mentransfer uang untuk dipegang Bryan sementara.
create table public.accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  account_type text not null default 'bank'
    check (account_type in ('cash', 'bank', 'e_wallet', 'savings', 'other')),
  -- holder = siapa yang secara fisik memegang/mengelola uang;
  -- owner = pemilik dana pribadi. owner null berarti dana milik bersama.
  holder_id bigint references public.people (id) on delete set null,
  owner_person_id bigint references public.people (id) on delete restrict,
  is_shared boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint accounts_name_not_blank check (char_length(trim(name)) > 0),
  constraint accounts_owner_matches_shared_status check (
    (is_shared and owner_person_id is null)
    or (not is_shared and owner_person_id is not null)
  )
);

-- Satu buku kas untuk semua arus uang.
-- income: dari luar -> rekening; expense/bill: rekening -> luar;
-- transfer/saving: antar rekening. Saldo selalu dihitung dari tabel ini.
create table public.ledger_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  entry_type text not null
    check (entry_type in ('income', 'expense', 'bill', 'transfer', 'saving', 'adjustment')),
  category text not null default 'other'
    check (category in ('daily', 'personal', 'shopee', 'application', 'savings', 'transfer', 'other')),
  amount bigint not null check (amount > 0),
  from_account_id bigint references public.accounts (id) on delete restrict,
  to_account_id bigint references public.accounts (id) on delete restrict,
  used_by_person_id bigint references public.people (id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  constraint ledger_has_an_account check (from_account_id is not null or to_account_id is not null),
  constraint ledger_accounts_are_different check (
    from_account_id is null or to_account_id is null or from_account_id <> to_account_id
  )
);

create index ledger_entries_entry_date_idx on public.ledger_entries (entry_date desc);
create index ledger_entries_used_by_date_idx on public.ledger_entries (used_by_person_id, entry_date desc);
create index ledger_entries_from_account_idx on public.ledger_entries (from_account_id);
create index ledger_entries_to_account_idx on public.ledger_entries (to_account_id);

-- Definisi tagihan berulang. Nilai tagihan dapat diubah per bulan pada bill_instances.
create table public.recurring_bills (
  id bigint generated by default as identity primary key,
  name text not null,
  bill_category text not null
    check (bill_category in ('personal', 'shopee', 'application', 'other')),
  responsible_person_id bigint references public.people (id) on delete set null,
  default_source_account_id bigint references public.accounts (id) on delete set null,
  default_amount bigint not null check (default_amount > 0),
  due_day smallint check (due_day between 1 and 31),
  is_active boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  constraint recurring_bills_name_not_blank check (char_length(trim(name)) > 0)
);

-- Baris tagihan untuk satu bulan. Tidak ada tagihan yang dibuat otomatis tersembunyi;
-- panggil fungsi create_bill_instances saat awal bulan.
create table public.bill_instances (
  id bigint generated by default as identity primary key,
  recurring_bill_id bigint not null references public.recurring_bills (id) on delete cascade,
  bill_month date not null,
  amount_due bigint not null check (amount_due > 0),
  status text not null default 'pending' check (status in ('pending', 'paid', 'skipped')),
  paid_on date,
  payment_entry_id bigint unique references public.ledger_entries (id) on delete restrict,
  note text,
  created_at timestamptz not null default now(),
  unique (recurring_bill_id, bill_month),
  constraint bill_instances_month_is_first_day check (bill_month = date_trunc('month', bill_month)::date),
  constraint bill_instances_payment_matches_status check (
    (status = 'paid' and paid_on is not null and payment_entry_id is not null)
    or (status in ('pending', 'skipped') and paid_on is null and payment_entry_id is null)
  )
);

create index bill_instances_month_idx on public.bill_instances (bill_month desc, status);

create table public.savings_goals (
  id bigint generated by default as identity primary key,
  name text not null,
  target_amount bigint not null check (target_amount > 0),
  target_date date,
  is_active boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  constraint savings_goals_name_not_blank check (char_length(trim(name)) > 0)
);

-- Setiap setoran ke target harus merujuk ke satu perpindahan ledger ke rekening tabungan.
create table public.savings_contributions (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.savings_goals (id) on delete cascade,
  ledger_entry_id bigint not null unique references public.ledger_entries (id) on delete restrict,
  contributed_by_person_id bigint references public.people (id) on delete set null,
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now()
);

create index savings_contributions_goal_idx on public.savings_contributions (goal_id);

-- Data awal: silakan ganti nama rekening jika perlu. Tidak ada nominal awal agar tidak salah catat.
insert into public.people (name, is_custodian)
values ('Bryan', false), ('Maddy', true)
on conflict (name) do update set is_custodian = excluded.is_custodian;

insert into public.accounts (name, account_type, holder_id, is_shared)
select 'Saldo Utama Maddy', 'bank', p.id, true
from public.people p where p.name = 'Maddy'
on conflict (name) do nothing;

insert into public.accounts (name, account_type, holder_id, is_shared)
select 'Uang Bryan', 'cash', p.id, true
from public.people p where p.name = 'Bryan'
on conflict (name) do nothing;

insert into public.accounts (name, account_type, holder_id, is_shared)
select 'Tabungan Bersama', 'savings', p.id, true
from public.people p where p.name = 'Maddy'
on conflict (name) do nothing;

-- Membuat daftar tagihan bulan tertentu dari recurring_bills yang masih aktif.
create or replace function public.create_bill_instances(p_month date)
returns integer
language plpgsql
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if p_month <> date_trunc('month', p_month)::date then
    raise exception 'p_month harus tanggal pertama dalam bulan tersebut';
  end if;

  insert into public.bill_instances (recurring_bill_id, bill_month, amount_due)
  select id, p_month, default_amount
  from public.recurring_bills
  where is_active
  on conflict (recurring_bill_id, bill_month) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

-- Saldo per rekening. Transfer tidak mengubah total uang bersama, hanya berpindah tempat.
create or replace view public.v_account_balances
with (security_invoker = true) as
select
  a.id,
  a.name,
  a.account_type,
  a.holder_id,
  p.name as holder_name,
  p.is_custodian as holder_is_custodian,
  a.owner_person_id,
  owner.name as owner_name,
  owner.is_custodian as owner_is_custodian,
  a.is_shared,
  a.is_active,
  coalesce(sum(case when l.to_account_id = a.id then l.amount else 0 end), 0)
    - coalesce(sum(case when l.from_account_id = a.id then l.amount else 0 end), 0) as balance
from public.accounts a
left join public.people p on p.id = a.holder_id
left join public.people owner on owner.id = a.owner_person_id
left join public.ledger_entries l on l.from_account_id = a.id or l.to_account_id = a.id
group by a.id, p.name, p.is_custodian, owner.name, owner.is_custodian;

-- Total gabungan mencakup dana bersama + dana pribadi Bryan + dana pribadi Maddy.
-- Sementara total_shared_money hanya menunjukkan dana yang benar-benar milik bersama.
create or replace view public.v_shared_overview
with (security_invoker = true) as
select
  coalesce(sum(balance), 0) as total_combined_money,
  coalesce(sum(balance) filter (where is_shared), 0) as total_shared_money,
  coalesce(sum(balance) filter (where not is_shared and owner_name = 'Bryan'), 0) as bryan_personal_money,
  coalesce(sum(balance) filter (where not is_shared and owner_name = 'Maddy'), 0) as maddy_personal_money,
  coalesce(sum(balance) filter (where holder_is_custodian), 0) as total_held_by_maddy,
  coalesce(sum(balance) filter (where not coalesce(holder_is_custodian, false)), 0) as total_held_by_others,
  coalesce(sum(balance) filter (where is_shared and holder_is_custodian), 0) as shared_money_held_by_maddy,
  coalesce(sum(balance) filter (where is_shared and not coalesce(holder_is_custodian, false)), 0) as shared_money_held_by_others,
  coalesce(sum(balance) filter (where account_type = 'savings'), 0) as total_savings
from public.v_account_balances;

-- Pemakaian per orang per bulan, termasuk pembayaran tagihan yang diberi used_by_person_id.
create or replace view public.v_person_monthly_usage
with (security_invoker = true) as
select
  date_trunc('month', l.entry_date)::date as month,
  p.id as person_id,
  p.name as person_name,
  coalesce(sum(l.amount) filter (where l.category = 'daily'), 0) as daily_usage,
  coalesce(sum(l.amount) filter (where l.category = 'personal'), 0) as personal_usage,
  coalesce(sum(l.amount) filter (where l.category = 'shopee'), 0) as shopee_usage,
  coalesce(sum(l.amount) filter (where l.category = 'application'), 0) as application_usage,
  coalesce(sum(l.amount), 0) as total_usage
from public.ledger_entries l
join public.people p on p.id = l.used_by_person_id
where l.entry_type in ('expense', 'bill')
group by 1, p.id, p.name;

-- Arus uang dan pemakaian total bulanan. saving_added adalah perpindahan ke rekening tabungan.
create or replace view public.v_monthly_cashflow
with (security_invoker = true) as
select
  date_trunc('month', entry_date)::date as month,
  coalesce(sum(amount) filter (where entry_type = 'income'), 0) as money_in,
  coalesce(sum(amount) filter (where entry_type in ('expense', 'bill')), 0) as total_usage,
  coalesce(sum(amount) filter (where category = 'daily' and entry_type in ('expense', 'bill')), 0) as daily_usage,
  coalesce(sum(amount) filter (where category = 'personal' and entry_type in ('expense', 'bill')), 0) as personal_usage,
  coalesce(sum(amount) filter (where category = 'shopee' and entry_type in ('expense', 'bill')), 0) as shopee_usage,
  coalesce(sum(amount) filter (where category = 'application' and entry_type in ('expense', 'bill')), 0) as application_usage,
  coalesce(sum(amount) filter (where entry_type = 'bill'), 0) as bills_paid,
  coalesce(sum(amount) filter (where entry_type = 'saving'), 0) as saving_added
from public.ledger_entries
group by 1;

-- Total tagihan yang harus dibayar dan yang sudah dibayar per bulan.
create or replace view public.v_monthly_bill_summary
with (security_invoker = true) as
select
  bill_month,
  coalesce(sum(amount_due), 0) as total_due,
  coalesce(sum(amount_due) filter (where status = 'paid'), 0) as total_paid,
  coalesce(sum(amount_due) filter (where status = 'pending'), 0) as total_pending,
  count(*) filter (where status = 'pending') as pending_count
from public.bill_instances
group by bill_month;

-- Progres setiap target tabungan. saldo_tabungan tetap terlihat di v_shared_overview.
create or replace view public.v_savings_goal_progress
with (security_invoker = true) as
select
  g.id,
  g.name,
  g.target_amount,
  g.target_date,
  g.is_active,
  coalesce(sum(c.amount), 0) as saved_amount,
  greatest(g.target_amount - coalesce(sum(c.amount), 0), 0) as remaining_amount,
  round(coalesce(sum(c.amount), 0)::numeric / g.target_amount * 100, 2) as progress_percent
from public.savings_goals g
left join public.savings_contributions c on c.goal_id = g.id
group by g.id;

-- Keamanan: hanya akun Bryan/Maddy yang dipetakan di people.auth_user_id yang bisa mengakses data.
-- Setelah keduanya membuat akun Supabase Auth, jalankan di SQL Editor (ganti email):
-- update public.people set auth_user_id = (select id from auth.users where email = 'bryan@email.com') where name = 'Bryan';
-- update public.people set auth_user_id = (select id from auth.users where email = 'maddy@email.com') where name = 'Maddy';
create or replace function public.is_finance_member()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.people where auth_user_id = auth.uid()
  );
$$;

alter table public.people enable row level security;
alter table public.accounts enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.recurring_bills enable row level security;
alter table public.bill_instances enable row level security;
alter table public.savings_goals enable row level security;
alter table public.savings_contributions enable row level security;

create policy "Finance members can read people"
  on public.people for select to authenticated using (public.is_finance_member());
create policy "Members can update their own profile"
  on public.people for update to authenticated
  using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

create policy "Finance members manage accounts"
  on public.accounts for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());
create policy "Finance members manage ledger"
  on public.ledger_entries for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());
create policy "Finance members manage recurring bills"
  on public.recurring_bills for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());
create policy "Finance members manage bill instances"
  on public.bill_instances for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());
create policy "Finance members manage savings goals"
  on public.savings_goals for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());
create policy "Finance members manage savings contributions"
  on public.savings_contributions for all to authenticated
  using (public.is_finance_member()) with check (public.is_finance_member());

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.v_account_balances, public.v_shared_overview,
  public.v_person_monthly_usage, public.v_monthly_cashflow,
  public.v_monthly_bill_summary, public.v_savings_goal_progress to authenticated;
grant execute on function public.create_bill_instances(date), public.is_finance_member() to authenticated;

-- Contoh pencatatan (jalankan setelah nominal/rekening Anda sesuaikan):
-- 1) Modal awal Rp1.000.000 yang dipegang Maddy
-- insert into public.ledger_entries (entry_type, amount, to_account_id, note)
-- select 'income', 1000000, id, 'Modal awal' from public.accounts where name = 'Saldo Utama Maddy';
--
-- 2) Maddy mengirim Rp100.000 kepada Bryan (uang hanya berpindah pemegang)
-- insert into public.ledger_entries (entry_type, category, amount, from_account_id, to_account_id, note)
-- select 'transfer', 'transfer', 100000, m.id, b.id, 'Kebutuhan Bryan'
-- from public.accounts m cross join public.accounts b
-- where m.name = 'Saldo Utama Maddy' and b.name = 'Uang Bryan';
--
-- 3) Bryan memakai Rp25.000 untuk kebutuhan harian
-- insert into public.ledger_entries (entry_type, category, amount, from_account_id, used_by_person_id, note)
-- select 'expense', 'daily', 25000, a.id, p.id, 'Makan'
-- from public.accounts a cross join public.people p
-- where a.name = 'Uang Bryan' and p.name = 'Bryan';
